wp-media/imagify-plugin

inc/functions/attachments.php

Fixes a problem where some image sizes are not listed in the settings: those sizes use a numeric identifier.

Fixes #117

---

inc/classes/class-imagify-assets.php
inc/functions/compat.php

Make sure Heartbeat is registered when it is needed. When a script that depends on Heartbeat is enqueued, register Heartbeat back if it has been deregistered.

Fixes #140: WP Engine breaks the bulk optimization

---

inc/3rd-party/amazon-s3-and-cloudfront/inc/classes/class-imagify-as3cf.php
inc/common/attachments.php

Introduced the filter `imagify_auto_optimize_attachment` allowing to prevent automatic optimization for a specific attachment.

Fixes #134: Disable auto optimization for specific file formats

---

inc/3rd-party/3rd-party.php
inc/3rd-party/nextgen-gallery/inc/admin/enqueue.php
inc/3rd-party/nextgen-gallery/inc/functions/common.php
inc/3rd-party/wp-real-media-library.php

This prevents this plugin to enqueue its outdated version of SweetAlert on the screens we use ours: some of our notices, bulk optimization page, settings page, NGG bulk optimization page.

Fixes #152: compatibility with WP Real Media Library plugin

---

inc/classes/class-imagify-admin-ajax-post.php
inc/functions/admin-stats.php
inc/functions/common.php

Introduced `imagify_unlimit_sql_joins()` to prevent hosts to limit the number of `JOIN`s in SQL queries.

Fixes #162: release the JOIN kraken

---

inc/classes/class-imagify-assets.php

Use a very low hook priority to enqueue Imagify styles and scripts: this allows to re-register heartbeat after Heartbeat Control plugin unregistered it.

Fixes #163: compatibility with Heartbeat Control

---

inc/3rd-party/3rd-party.php
inc/3rd-party/formidable-pro/formidable-pro.php
inc/3rd-party/formidable-pro/inc/classes/class-imagify-formidable-pro.php
inc/admin/upgrader.php
inc/functions/admin-stats.php
inc/functions/common.php

When a query is made by Imagify, the `pre_get_posts` hook from FFP is removed (and put back later).

Fixes #166: compatibility Formidable Forms Pro

---

assets/js/jquery.twentytwenty.js
assets/js/jquery.twentytwenty.min.js

TwentyTwenty ("Compare Original VS Optimized" button): prevent displaying multiple buttons.
While we're at it, insert this button when the "Previous" and "Next" buttons from the media modal are clicked (library in grid view).
Also, removed the `waitContent` + `setInterval()` wrappers, as they are useless (events are delegated).

Fixes #177: multiple compare buttons

---

assets/js/jquery.twentytwenty.js
assets/js/jquery.twentytwenty.min.js
inc/admin/meta-boxes.php
inc/classes/class-imagify-abstract-attachment.php

In TwentyTwenty, try first to grab the image `width` and `height` attributes to get its dimensions. If it fails, then use the computed styles. This is to prevent to have an image with a height and width of 0. Also, improved a bit the whole code and enabled the linter in this section.

Fixes #180: Images are not showing in the comparison tool

---

inc/3rd-party/nextgen-gallery/inc/admin/ajax.php
inc/admin/ui/bulk.php
inc/classes/class-imagify-admin-ajax-post.php
inc/functions/admin-stats.php
inc/functions/attachments.php
uninstall.php

Thinking it wasn't used, the first idea was to remove the `imagify_large_library` transient.
But in fact it is used, it's just a bit messed up.
TL;DR: consistency, small fixes, new helper function.

Large library transient

---

inc/classes/class-imagify-admin-ajax-post.php
inc/functions/admin.php
inc/functions/common.php

Improved lang detection in `imagify_get_wp_rocket_url()` and `imagify_get_external_url()`.
Instead of focusing on "sub-language" (the locale, like 'fr_FR'), use the "language family" (like 'fr', that regroups 'fr_FR' and 'fr_BE'). This way works in most cases, and at least for the languages we use.
Introduced `imagify_get_current_lang_in()` and `imagify_get_locale()`.

Improves lang detection

---

inc/classes/class-imagify-attachment.php

When an image is resized before optimization, save the new dimensions earlier, before the method `optimize()` ends because of an unsuccessful optimization.

Fixes #208

---

inc/3rd-party/amazon-s3-and-cloudfront/amazon-s3-and-cloudfront.php

Following PR #204, fixing #197:
- Keep compat' with old versions of the plugin WP Offload S3 that require the plugin Amazon Web Services.
- Keep compat' with new versions that do not require the plugin Amazon Web Services.

Fixes #197

---

inc/classes/class-imagify-admin-ajax-post.php
inc/classes/class-imagify-db.php
inc/functions/attachments.php

When a query is "prepared" (aka `vsprintf()`), escape the % characters that are parts of LIKE clauses.
Changed 2 methods signature to prevent having 4 parameters.

Escape % characters  for prepared SQL queries

---

inc/admin/custom-folders.php
inc/classes/class-imagify.php

In `imagify_sync_theme_plugin_files_on_update()`, the class `Imagify` from the new plugin was loaded, calling new code while old code is already loaded.
The solution is to patch `Imagify` for the updates from 1.7, and delay the job in `admin_init` instead of `upgrader_post_install`, using a transient.

Fixes fatal error on Imagify update

---

inc/classes/class-imagify-admin-ajax-post.php
inc/classes/class-imagify-files-list-table.php

There's still one `FILTER_SANITIZE_NUMBER_INT` left, because the value is not required.

Use `FILTER_VALIDATE_INT` instead of `FILTER_SANITIZE_NUMBER_INT`

---

inc/admin/upgrader.php
inc/classes/class-imagify-admin-ajax-post.php
inc/classes/class-imagify-custom-folders.php
inc/classes/class-imagify-files-list-table.php
inc/classes/class-imagify-files-scan.php
inc/classes/class-imagify-filesystem.php
views/part-settings-custom-folders.php
views/part-settings-row-custom-folder.php

Basically, `ABSPATH` is not the path site's root folder.

Fixes #258: support for content folders outside WP folder

---

inc/classes/class-imagify-filesystem.php

Improved Imagify_Filesystem->make_dir() chmod tests.
There is no need to test chmod on folders that we don't create a sub-folder in.

Fixes #287: Directory creation may fail

---

inc/classes/class-imagify-filesystem.php

Sometimes `$_SERVER['DOCUMENT_ROOT']` does not "fit" `ABSPATH` at all (symlink?). Using `realpath()` fixes the issue.

Fixes #286: Imagify_Filesystem::get_site_root() failure on multisite

---

views/part-settings-webp.php

The process to have webp images does not "convert" images, in the sense of "replace"; but "add" webp images along the non-webp images. By changing this label we try to make it more clear for the users.

Improved label of the webp option

---

inc/classes/class-imagify-files-scan.php

Because of `$folders = array_flip( $folders );` earlier, the needles used in `strpos()` were integers (array numeric keys before `array_flip()`).

Fixes #376: strpos() on non-string needles

---

composer.json

Use [Composer for WordPress](https://github.com/dangoodman/composer-for-wordpress) Composer plugin as dev dependency to "namespace" the Composer class loader itself. This will prevent conflicts with plugins using an old version of Composer.

Fixes #372: Conflict with plugins using outdated Composer

---

inc/3rd-party/regenerate-thumbnails/classes/Main.php

Make sure the REST object is set before getting its namespace.

Fixes #387: regenerate thumbnails php notice

---

inc/3rd-party/wp-rocket/classes/Main.php

Even if `get_rocket_cdn_cnames()` has not been deprecated, use the new method is more future-proof.

Closes #425: Adapt compatibility to WP Rocket 3.4

---

classes/Webp/Picture/Display.php

Moved the width and height attributes from the `<picture>` tags to the `<img>` tags, so the markup is valid.

Closes #421: No width/height attributes on <picture> tags

---

inc/3rd-party/enable-media-replace/classes/Main.php
inc/3rd-party/enable-media-replace/enable-media-replace.php
inc/3rd-party/regenerate-thumbnails/classes/Main.php
inc/classes/class-imagify-auto-optimization.php

WP now uses `wp_update_attachment_metadata()` after each thumbnail creation instead of one call after all thumbnails are created.
Since Imagify uses a hook in this function to launch the auto-optimization, this change would break the process.
This PR prevents the multiple optimisations and keeps the previous behaviour in Imagify.
This also updates the compatibility with the "Regenerate Thumbnails" and "Enable Media Replace" plugins.
This also adds compatibility with "Enable Media Replace" plugin 3.3.

Compatibility with WP 5.3: save upload progress after each thumbnail

---

inc/classes/class-imagify-auto-optimization.php

WP 5.3 introduces a process to recover from media upload failures. Basically, if php crashes (not enough memory, etc), an ajax request will be done to create the missing thumbnails.
Imagify will trigger the auto-optimization once all thumbnails are created.

Compatibility with WP 5.3: upload failures

---

classes/Webp/Picture/Display.php

Make sure the `srcset` attribute on `<source>` tag is not empty.
If the original `<img/>` tag does not contain a `srcset` attribute, the original image URL is added to the `<source/>`’s `srcset` attribute.

Fixes #455: Empty `srcset` attribute on `<source/>` tags

---

inc/3rd-party/amazon-s3-and-cloudfront/amazon-s3-and-cloudfront.php

Prevent a fatal error with WP Media Offload 2.3

Fixes #456: WP Offload Media recent update breaks Imagify

---

classes/Webp/Picture/Display.php
imagify.php
inc/3rd-party/amazon-s3-and-cloudfront/amazon-s3-and-cloudfront.php
package.json
readme.txt

* Fixes #455: webp image not showing when using the `<picture>` method and the original `<img/>` does not have a `srcset` attribute.
* Fixes #456: a fatal error with WP Offload Media 2.3.

Branch 1.9.8.1

---

classes/Imagifybeat/Actions.php
imagify.php

Since `get_size_data()` can return an empty array, make sure the array keys are set before using them.

Prevent php notices

---

inc/classes/class-imagify.php

When sending a file for optimization, use HTTP/1.1 by default: the filter `imagify_curl_http_version_1_0` now defaults to `false`.
Fixes #465.

Prevent the "chunky upload" error

---

inc/classes/class-imagify-auto-optimization.php
inc/deprecated/classes/class-imagify-auto-optimization-deprecated.php

Manual tests so far:
- Auto-optimize on upload in WP >= 5.3: ✅ 
- Auto-optimize on upload in WP < 5.3: ✅ 
- Compatibility with "Regenerate Thumbnails" still working (WP >= 5.3): ✅ 
- Compatibility with "Enable Media Replace" still working (WP >= 5.3): ❌ (but was broken before this PR, see #493).
Fixes #491.

Fixes #491: Auto-optimization on image upload doesn't optimize thumbnails

---

inc/3rd-party/enable-media-replace/classes/Main.php
inc/3rd-party/enable-media-replace/enable-media-replace.php
inc/classes/class-imagify-auto-optimization.php
inc/deprecated/classes/class-imagify-auto-optimization-deprecated.php
inc/deprecated/classes/class-imagify-enable-media-replace-deprecated.php

This fixes our compatibility with the plugin "Enable Media Replace". It was broken since EMR updated its code to adapt to WordPress 5.3’s new upload process.
Sum up:
- Use the hook `'wp_handle_replace'` to initiate the class, instead of `'emr_unfiltered_get_attached_file'`.
- Removed some `if` statements and tests in `init()` that are not needed anymore.
- The old webp file paths are stored in `init()` now: like explained in the DocBlock, this prevents some orphan files from being kept indefinitely when the user chooses not to rename the files.
- Deprecate the method `store_old_backup_path()`, as it is not needed anymore: the old backup path is already correct and the old webp file paths are stored in `init()`.
Fixes #493.
Tests done locally. I will explain the procedure to the QA team.

Fixes #493: compatibility with plugin "Enable Media Replace" broken with WP 5.3
