imagify.php, inc/3rd-party/nextgen-gallery/inc/classes/class-attachment.php, inc/classes/abstracts/abstract-attachment.php, inc/classes/class-attachment.php, inc/functions/process.php, readme.txt
Resize Images using WP Image Editor
=> Version 1.5.7

inc/functions/admin-ui.php, languages/imagify-de_DE.po, languages/imagify-de_DE_formal.po, languages/imagify-es_ES.po, languages/imagify-fr_FR.po, languages/imagify-it_IT.po, languages/imagify.pot
Replaced the string "determinate the best plan for you" by "determine the best plan for you".
=> Fixes #50.

inc/admin/ui/bulk.php, languages/imagify-de_DE.po, languages/imagify-de_DE_formal.po, languages/imagify-es_ES.po, languages/imagify-fr_FR.po, languages/imagify-it_IT.po, languages/imagify.pot
Replaced the string "You optimized %s images of your website" by "You optimized %s of your website's images".
=> Fixes #51.

inc/functions/process.php
Added a hook in `imagify_do_async_job()` to filter the arguments.
=> Fixes #46.

inc/3rd-party/hosting/wpengine.php, inc/3rd-party/nextgen-gallery/inc/admin/bulk.php, inc/3rd-party/nextgen-gallery/inc/admin/heartbeat.php, inc/3rd-party/nextgen-gallery/inc/functions/admin-stats.php, inc/functions/admin-stats.php, inc/functions/admin.php, inc/functions/deprecated.php
Improve bulk page performance for huge libraries
=> Closes #79

inc/compat.php
Added `array_replace()` polyfill for php 5.2.
=> Fixes #107

composer.json
Missing fields in `composer.json`.
=> Fixes #116

inc/3rd-party/nextgen-gallery/inc/admin/ajax.php, inc/admin/ajax.php, inc/admin/ui/notices.php, inc/functions/admin-ui.php, inc/functions/common.php, phpcs.xml
New helpers, more user capacity tests.
=> Improves admin ajax/post callbacks

assets/js/bulk.js, assets/js/bulk.min.js, inc/admin/ui/bulk.php
Fixes the width of the "Optimized size" in the bulk optimization page.
=> Fixes #142: Statistics Layout could be broken

inc/classes/class-imagify-abstract-attachment.php, inc/classes/class-imagify-abstract-db.php
=> Made "abstract" classes really abstract

inc/functions/process.php
=> Fixes #161: compatibility with plugins that use cookies.

inc/3rd-party/3rd-party.php, inc/3rd-party/hosting/siteground.php
Change the User-Agent for HTTP requests "to self".
=> Fixes #153: compatibility with SiteGround

inc/3rd-party/amazon-s3-and-cloudfront/inc/classes/class-imagify-as3cf.php, inc/3rd-party/nextgen-gallery/inc/classes/class-imagify-ngg-db.php, inc/classes/class-imagify-abstract-db.php, inc/classes/class-imagify-admin-ajax-post.php, inc/classes/class-imagify-db.php, inc/functions/admin-stats.php, inc/functions/admin.php, inc/functions/common.php, inc/functions/deprecated.php
This is the last one for this version.
=> Introduces class `Imagify_DB`

inc/functions/compat-spl-autoload.php, inc/functions/compat.php
Moved the polyfill for the SPL autoloader to a separate file to prevent compiler notices with php 7.2.
=> Fixes #189

inc/3rd-party/amazon-s3-and-cloudfront/amazon-s3-and-cloudfront.php, inc/3rd-party/amazon-s3-and-cloudfront/inc/classes/class-imagify-as3cf-attachment.php, inc/3rd-party/amazon-s3-and-cloudfront/inc/classes/class-imagify-as3cf.php
Improved tests for S3 presence.
=> Fixes #197

assets/js/jquery.twentytwenty.js, assets/js/jquery.twentytwenty.min.js
Fixed the comparison tool, that was displaying multiple handles.
=> Fixes #198

inc/3rd-party/hosting/siteground.php
Parse the site URL instead of using unreliable `$_SERVER` var.
=> Fixes #213

inc/3rd-party/hosting/siteground.php
For internal http requests, change the User-Agent only to admin-ajax.php, admin-post.php, and wp-cron.php.
=> Fixes #184

inc/3rd-party/3rd-party.php, inc/3rd-party/amazon-s3-and-cloudfront/inc/classes/class-imagify-as3cf-attachment.php, inc/3rd-party/nextgen-gallery/inc/classes/class-imagify-ngg-attachment.php, inc/3rd-party/regenerate-thumbnails/inc/classes/class-imagify-regenerate-thumbnails.php, inc/3rd-party/regenerate-thumbnails/regenerate-thumbnails.php, inc/classes/class-imagify-abstract-attachment.php, inc/classes/class-imagify-attachment.php, inc/classes/class-imagify-file-attachment.php, inc/functions/common.php
Side note: since Regenerate Thumbnails doesn't seem to support S3, support for RT + S3 together has not been added.
=> Fixes #211: added support for plugin Regenerate Thumbnails

inc/admin/upgrader.php
Change the hook used to reset opcache.
This one is safer because it is triggered after the maintenance mode is disabled. Also, this is the same hook that WordPress will use when this functionnality is released in core.
=> Fixes #236: OPcache reset

inc/3rd-party/nextgen-gallery/inc/classes/class-imagify-ngg-attachment.php, inc/3rd-party/nextgen-gallery/inc/classes/class-imagify-ngg-dynamic-thumbnails-background-process.php, inc/3rd-party/nextgen-gallery/inc/common/attachments.php, inc/3rd-party/nextgen-gallery/nextgen-gallery.php, inc/classes/class-imagify-abstract-attachment.php, inc/classes/class-imagify-custom-folders.php, inc/classes/class-wp-async-request.php, inc/classes/class-wp-background-process.php, inc/functions/common.php, phpcs.xml
Added process to optimize thumbnails that are created dynamically by NextGen Gallery.
=> Fixes #245: NextGen dynamic thumbnails

assets/js/options.js, assets/js/options.min.js, inc/classes/class-imagify-admin-ajax-post.php, inc/classes/class-imagify-custom-folders.php, inc/classes/class-imagify-files-iterator.php, inc/classes/class-imagify-files-recursive-iterator.php, inc/classes/class-imagify-files-scan.php, inc/classes/class-imagify-filesystem.php, views/part-settings-custom-folders.php
Allow to optimize "custom files" located in the uploads folder.
=> Fixes #240: custom files in uploads folder

inc/3rd-party/amazon-s3-and-cloudfront/inc/classes/class-imagify-as3cf-attachment.php, inc/3rd-party/amazon-s3-and-cloudfront/inc/classes/class-imagify-as3cf.php, inc/3rd-party/nextgen-gallery/inc/classes/class-imagify-ngg-attachment.php, inc/3rd-party/regenerate-thumbnails/inc/classes/class-imagify-regenerate-thumbnails.php, inc/3rd-party/wp-retina-2x/inc/classes/class-imagify-wp-retina-2x-core.php, inc/3rd-party/wp-retina-2x/inc/classes/class-imagify-wp-retina-2x.php, inc/admin/media.php, inc/admin/upload.php, inc/classes/class-imagify-abstract-attachment.php, inc/classes/class-imagify-admin-ajax-post.php, inc/classes/class-imagify-attachment.php, inc/classes/class-imagify-file-attachment.php, inc/classes/class-imagify-files-list-table.php, inc/classes/class-imagify-filesystem.php, inc/classes/class-imagify-views.php, inc/functions/admin-stats.php, inc/functions/admin-ui.php, inc/functions/api.php, inc/functions/attachments.php, inc/functions/i18n.php, inc/functions/process.php
It also brings hooks that were missing.
=> Fixes #252: pdf support

inc/admin/upgrader.php
Introduced `imagify_reset_opcache()`.
=> Improved opcache reset on plugin upgrade

assets/css/pricing-modal.css, assets/css/pricing-modal.min.css, views/modal-payment.php
Also fixed some typos and removed the dates from the tweets.
=> Improved wording in payment modal

inc/classes/class-imagify-assets.php
Improved Heartbeat re-registering:
- WP 5.0 introduced a new 'wp-hooks' dependency.
- The script is also re-localized.
=> Closes #364: Heartbeat re-registering

classes/Context/CustomFolders.php, classes/Context/Noop.php, classes/Context/WP.php, classes/Imagifybeat/Actions.php, classes/Imagifybeat/Core.php, classes/Stats/OptimizedMediaWithoutWebp.php, classes/Traits/InstanceGetterTrait.php, classes/Webp/Display.php, classes/Webp/Picture/Display.php, classes/Webp/RewriteRules/Display.php, inc/3rd-party/amazon-s3-and-cloudfront/classes/Main.php, inc/3rd-party/enable-media-replace/classes/Main.php, inc/3rd-party/formidable-pro/classes/Main.php, inc/3rd-party/nextgen-gallery/classes/Context/NGG.php, inc/3rd-party/nextgen-gallery/classes/DynamicThumbnails.php, inc/3rd-party/nextgen-gallery/classes/Main.php, inc/3rd-party/regenerate-thumbnails/classes/Main.php, inc/3rd-party/wp-rocket/classes/Main.php, inc/classes/class-imagify-admin-ajax-post.php, inc/classes/class-imagify-plugin.php
Some hosts find it funny to rename the file `FakeSingletonTrait.php` because its name contains "fake", so the trait has been renamed into `InstanceGetterTrait`.
:facepalm:
=> Closes #386: Singleton trait flagged by hosts

inc/classes/class-imagify-views.php
Use a user capacity as `add_media_page()`’s 3rd argument instead of a user capacity check.
=> Fixes #441: "Other Media" menu capacity issue

classes/Webp/RewriteRules/Nginx.php
As we have confirmation from one user that removing "final" worked for them, sending this Pull request.
Issue: https://github.com/wp-media/imagify-plugin/issues/423
Ticket: https://secure.helpscout.net/conversation/1138088855/158359?folderId=676702
=> Fix NGINX Rewrite Rules

.gitignore, inc/classes/class-imagify.php
Fixes #539 .
Add a check for php8 CurlHandle object
=> Fix PHP8-cURL Compatibility
